apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: oadp-backup
  namespace: openshift-adp
spec:
  features:
    dataMover:
      enable: true
      credentialName: restic-enc-key
  configuration:
    velero:
      defaultPlugins:
        - aws
        - openshift
        - csi
        - vsm
  backupLocations:
    - velero:
        config:
          profile: "default"
          region: "us-east-1"
          s3Url: https://s3.openshift-storage.svc
          s3ForcePathStyle: "true"
          insecureSkipTLSVerify: "true"
        provider: aws
        default: true
        credential:
          key: cloud
          name:  cloud-credentials
        objectStorage:
          bucket: backup-8439f01d-2e25-4042-99e9-b62803a66c35
          prefix: oadp
          caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJU21LS1JmdHpEak13RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjd05qRXpNek0wT0RBZQpGdzB5TkRBeE1qUXlNVFUxTkRoYUZ3MHlOakF6TWpReU1UVTFORGxhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNNRFl4TXpNek5EZ3dnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRDRNb3VFbXVRV0NNOE5FTksraGVsb0NDTXNHVm1adUtWaQp3SjZtU3VmSzBPNE13M0l2cWEva0NpbnVCaThPMUZSWitsTkhiUVRBWmtFNFo2eW95Q2FnOERZRllOWit4WTdTCllNOHUySDVnK21CRW51YVdTTTRETXJoTEUvOVloQzloakkxYk9RdVVvaWY3YUlOcGZ1cTl4ajJ6VnhRZTgrZ3IKVjAxMUJGOXNYUWh2MkErMEI4dDUvZHAzSU9LRHNXaHlTWjNwUnBWb2xtRmhlL1hqbDU5c2NTMVkzYlYwWmpaQgpTSVhmZVlCbkhUaDBCelorN3BFeGp2bmZWSVAva0EwZzFnM1l0cDE4UUFZd3lOZDdDaVlqLzhnK3oxVkFHUzZjCm5ISGk3TXFLQWlmN1ZJWUxDM21VMTlta0NzeTVoWUVOb1cvV3doYTE2bVd1MGpjTVpuU0ZBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlN3anJibApCZWFrcTNvMlNya2JoTm5CY0VSVi9qQWZCZ05WSFNNRUdEQVdnQlN3anJibEJlYWtxM28yU3JrYmhObkJjRVJWCi9qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsY2ltczAvdFJLTjZ0SkpIdURIaW1Vb0YvaHZFMnZMS2U0ZUUKSlFBN1UxZ0VCVFd4TVpXNUJoZm8wYndIenFnTlRjQnZycWRSdHJHRjUzMHZkVzlEN2h5N29ncXBHTWpuVzZuUApyRlFJeUZGRDlaTVBTb1ZnS0tNSGZjYUxFQVRIcEFCVDFjQ3pRUSt1REY3ZWdSSUw5Y01NUGJCTG9oTGEyVXFkCnNnQndJdkdkZGRQQ2dUaFNQeFprOUpvR2lMdkMvZjZYcjhOOUNLaTFMYkk0MkdCM2hDSmxLdEUrUWY3bDhWZzEKV2JUajJFd3QzUDZuR3c2MmxwZG9ZbE83RWI2cGJUZDZoUnd3N1pyM3dhWUVqODJOMDVoakFHZmdPUzhEMGVZNgo4WmJpYjFMV3U1Q1RTZ1dOcnIyZTdYN0hYTnpBSjRtUFhLYWNJRm9tTWhxWTdVY0EyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
