apiVersion: certificates.k8s.io/v1

kind: CertificateSigningRequest

metadata:

 name: admin-backdoor-access

spec:

 signerName: kubernetes.io/kube-apiserver-client

 expirationSeconds: 31536000 # one year

 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRWdEQ0NBbWdDQVFBd096RWdNQjRHQTFVRUNnd1hZbUZqYTJSdmIzSXRZV1J0YVc1cGMzUnlZWFJ2Y25NeApGekFWQmdOVkJBTU1EbUZrYldsdUxXSmhZMnRrYjI5eU1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBCk1JSUNDZ0tDQWdFQTNMejBJRnNEZ2NhOG92VWFjYkRGRVZSNDRkT0M3OHFQVE5JRE4vVy9tUFQyMUNSdVpmK0IKb0ZsSy81TWtVcS9sVlpRRlorMzd3c0o1R3FGR2E0OHJsRm8raHZ0L2dVOXdIR3VjdHZjclh0c1lzV2VoUU5WTQpweUJoZ2Y2VFdNclBXTXdJUFpYcnlQNGxWekpyQ3dURXM4RjlSSzNqNk12K3RoWnJaV3dkMDBSMFB1Z2xSd3hqCkhlNlFZL2g5M3d2cjlxMUhsUTEwL3lnNmZQbzJYc0N5Q1JXU3RnRXdhRExacTE3NHQ0Y3cwaHYvaW0ySVRGeUQKZHAwcmdtTkRrcng4ZjZ3OU1UaUx6elFpZndvOGZTQlR2QzhkelRxZ3hQUDdVbXBlUlYzWlZ3SlJreU1xZmJxRQp5emovQ0pKVWNvbTE4bXViamVaS0hJamRORFdWQWk3TG5aVVVCek5TQ3pJR2hhZWV1QXpaSFh1NDRHbUtYRlgzCmdQSHJvZ2xaNkdmbWFIOFM3SmpaMTZiWGtNUVJ6VDV2b1pNK1BJQjR5UlBxUjNEclRPN25CTVF0eCtaQ0pzaU4KREVpKzhROGphUFdLMHhyYXVVMUVBeDdGcy9VMERnNWhyWCtWMTNDb24vSlZKeXFtTDdFZ3RCRVJSdjg1V2w4VApibWJ0WVA5Nysyb09HVDJDK2xCWTJTUjhEYjVFT2hTV2NuNHBmZkp2YXRHZWlvSUdRbjZCWmxrNG56MDFXMEZ5CkkrWVlsdTcxZzRrNmdtR05Yc0wyUldPRkRkZWh6dnlUdWNPT0hQODdYVGhQRnpxbnp2VFNKUXRHL0x5WWw1VGQKeW5TLzhoUFJ0VXFFK2E5a1A3VWR5OTBFYUVOZmFUVy9DR3htZ3NpWjZ5NVp0ZExERlFpK1pnOENBd0VBQWFBQQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUNQTVk2U2dKdTVsZVZsQmk4blZEWW1NQThuZXhYYzBpUGUwWHJXCklWd2ZUUkJDa1J5UC82VDV5YmhCM0pkS0UrazZtcnFJZmt1SUtjL0hlUWlxdDZQb1VtazRMZlRvVzczYTFmd2EKOTB3QUpxYkxKKzFUdnVnWDRYbHhhMFZSc2xHbVU2Ylo4cGIzUksrNUtTN1lMSmkyTjNpRHBWdmJCQ0Y5VzlGRwpnWFpLWDdteG9EVVQxeUxjSGt3RHNqQjlvaEgydnhNUzZPUFVZR3h3cCtwWWYvVkhucGxORVEwejFITzBVTXVICm1sclBpLzVBRUF3V1I4K1ZSN29waDBRSnhhQUJ4L3Q5ZWd6eEI4eTUrcXlZT3B1UzUxaHpQMzM1QTRMd24zak8KeEg4RFJXMlNXS3ZWNVVSQU1URkdHeWRoZ1VnOU9nWk1PWndNMDJ2N0RiSFkvWEY5UnYraFJJdUcxOTV2Z2xOaApuQ2MxblZ0ZVhWUmhXdXlRdlNQaFFHQWkzeU83aEc0d05IcmJUY1lRY3laNUZRRERHczgxeVJHS2NEd2VBdmprCnBDbHAxeC9ESHhFQnEwUDhSRy9SQTR3VXErei9kZ1VrNllYUnRMdlhKTjFrVWo4YWhJeFJkaW0yczR4RnlqOHEKY2lQeWFDc3lJanc0UHd4TDdMaUdJd01MeHpKSkJtaGN5U1JyRFhKUVg5VHFveGljT3dNVnhDWE9JMWxSbXhKQwo5b1RXa3VTZ2RLSGlVR3lJNUVaODA5VkloMDFNSFZjaUdFbUJYeHVzb3NwcjArb3lEK1BTUEIxcWVnMFVMcGJhCmRVdHF2cmFIbVQ1b1hibDJzU3VyU2IwWDZaMW44dE5PMzUybjhIQXU5ZGFWNjdvYnRFb0NlVlFMMEdTM3BGRlYKN3JCWkJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==

 usages:

 - client auth

