---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: mariadb
stringData:
  MARIADB_DATABASE: application
  MARIADB_USER: appuser
  MARIADB_PASSWORD: securepassword
  MARIADB_ROOT_PASSWORD: supersecurepassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  labels:
    app: mariadb
data:
  db.sql: |
    CREATE TABLE `application_logs` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `app` varchar(254) NOT NULL DEFAULT 'system',
    `message` varchar(254) NOT NULL,
    PRIMARY KEY (`id`)
    ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mariadb
        image: registry.ocp4.example.com:8443/redhattraining/mariadb:10.5
        resources: {}
        ports:
        - name: mariadb
          containerPort: 3306
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -v -b -u "root" -p"${MARIADB_ROOT_PASSWORD}" "mysql" -e "SHOW STATUS ;"
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -v -b -u "${MARIADB_USER}" -p"${MARIADB_PASSWORD}" "${MARIADB_DATABASE}" -e "SHOW TABLES ;"
        envFrom:
        - secretRef:
            name: mariadb
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: init-data
          mountPath: /docker-entrypoint-initdb.d
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
      - name: init-data
        configMap:
          name: database
          defaultMode: 0444
      terminationGracePeriodSeconds: 3
